### ISSUE TITLE
Services page

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#11]
WE can just copy this text & make the other links
http://bigskyinternetdesign.com/our-services.asp

**Comment by Kducey1** [comment]
So I tried to edit the services page to make it close to the big sky one. If you want to check it out. Its not completely done. Some of the services might need more of a description if you can think of one.

**Comment by cbruch** [comment]
Humm I can't see the changes

**Comment by Kducey1** [comment]
Hmm. That is odd. It is showing up on my computer:/ Um maybe try again? If that doesn't work let me know

I also didn't know what to put in the "why Choose Us?" Section on the "Services" page. If you cant think of anything to put there I can just remove it entirely

**Comment by cbruch** [comment]
Can you resend me the link please

**Comment by Kducey1** [comment]
file:///C:/Users/Kristen/Desktop/Big%20Sky%20Design/universal/services.html

**Comment by cbruch** [comment]
This link will not work as it is working off your desk top!

**Comment by Kducey1** [comment]
Dang :/ Okay. Im not sure what is going on. I'll try and get a hold of JT. Maybe he can help with this. I still dont have a full grasp on this stuff ahah

**Comment by cbruch** [comment]
Ok the new services page link worked! No CLUE!

**Comment by Kducey1** [comment]
Awesome! Glad it worked!

**Comment by Kducey1** [comment]
service page is completed
