### ISSUE TITLE
Copywrite Date needs to be added to footer.

### ISSUE THREAD

**Issue by Kducey1** [Kducey1/BigSkyInternetDesign#14]

**Comment by JT-Bruch** [comment]
What I would do is copy the footer section remove the guts and put the copywrite content from Big Sky in there and center it.

The hard part is going to be adding the JavaScript so it auto-generates the copywrite date.
To do that, get a copy of the copywrite.js that is on BigSky.
Add it to your js folder here.
Then look at the BigSky View Source (not inspect), and see how they are using the document and copy and paste the <p> that is in the copywrite section.

**Comment by Kducey1** [comment]
Added :)
