### ISSUE TITLE
All large background image

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#17]
We need to get these resized or saved for the web the are way to large.   Let me know if I need to help you with this.

**Comment by Kducey1** [comment]
I know how to resize photos, but I'm not sure how much to resize them too.
I resized them to the size the stock photos they came in, but clearly they are still to big :/

**Comment by JT-Bruch** [comment]
@Kducey1 
http://graphicdesign.stackexchange.com/questions/48751/how-to-reduce-the-size-of-a-png-with-in-ps-for-web

https://tinypng.com/

**Comment by Kducey1** [comment]
@JT-Bruch So I converted them all. See if it is faster for yall

**Comment by cbruch** [comment]
All the header images are still TO large. Most over a 2 mg. If you want I can resize them.

**Comment by JT-Bruch** [comment]
![image](https://cloud.githubusercontent.com/assets/7430562/19871040/ce77082a-9f78-11e6-9ef4-15712c99e3e1.png)
Looks like its only the contact.png and ipadiphone.jpg.  Also looks like you missed the spelling on the copywrite.js

**Comment by Kducey1** [comment]
I resized the images so it should be faster

**Comment by cbruch** [comment]
The index one needs to be smaller than 975KB
Scar is over 2 mb
Client is 2.28
Services is 2.9
Port is 1.9

**Comment by JT-Bruch** [comment]
![image](https://cloud.githubusercontent.com/assets/7430562/19873538/238cf156-9f85-11e6-9021-302da27dcc2f.png)
A good rule of thumb is to use the throttling tool in Chrome to see how the site loads on a subpar internet connection.

**Comment by cbruch** [comment]
OR just send me the link!!!
