### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#18]
I'd love a crazy pic like this one. this is on 123f
![image](https://cloud.githubusercontent.com/assets/14894254/19787209/2e081028-9c67-11e6-8ecb-a193535acfe7.png)

**Comment by Kducey1** [comment]
hahah okay. I actually have a picture really similar to that on the 404 page already. Great minds haha

Well I made a photo for the contact page since I couldn't find a free one. Tell me what you think!

**Comment by cbruch** [comment]
I don't know what F.... I can never see changes unless you send link! YUG!

**Comment by Kducey1** [comment]
Sorry that was my bad. I thought I committed the changes in github but it is taking forever. Give it a minute and it should work!

**Comment by Kducey1** [comment]
okay it just committed so it should update shortly

**Comment by cbruch** [comment]
Send link!!  LOL Still nothing :(

**Comment by cbruch** [comment]
Just gray screen!

**Comment by Kducey1** [comment]
https://kducey1.github.io/BigSkyInternetDesign/contact.html

try again

**Comment by cbruch** [comment]
OMG PERFECT!!!!!  LOVE IT LOVE IT LOVE IT!

**Comment by Kducey1** [comment]
hahahah awesome! Glad you like it. I was going to do one of kylie, but her ears were just too big
