### ISSUE TITLE
Home  - General Changes

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#19]
1. Top logo tick bigger
2. Clients to Testimonials ( I know BORING!)
3. Updates Guaranteed with 24 hours - Bigger & Bold
4. Faster Updates - text change - Guaranteed Unlimited Updates are included in our update/maintenance plans. 
5. Footer - need the copywrite js code to display the years. I will email that. & the copy write & godaddy icon all link to our FB page
6. Missing Autorizenet  logo -  I think it was there!
7. Contact & portfolio links goes to wrong page

**Comment by Kducey1** [comment]
These should all be fixed now
