### ISSUE TITLE
About Us 

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#20]
1. Paragraph at the top about us like on BSID

People make a company and the right people make the company a success. Our team of dedicated professionals' sole purpose is to provide professional service, yet on a very personal level. Each customer's needs are unique and we take the time to listen, to ensure the solutions offered are in the customer's best interest. Long term relationships are our goal. At Big Sky Internet Design “You are more than just a customer”.

Tom and Carrie, owners of Exceleration Designs, Inc, have been designing websites since 1998. Big Sky Internet Design and Aggieland Website Design are divisions of Exceleration Designs.  Big Sky Internet Design is the backbone of the business and has been highly successful by offering unsurpassed levels of customer service.  Ask ANY of our customers!

Then we do like you wanted just pictures of us, then going to the text.

**Comment by Kducey1** [comment]
Added the paragraph!
