### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#22]
Let's pull map since it goes to our house!  LOL

We will need to put in this form
http://bigskyinternetdesign.com/contact-us.asp

Not sure if you can do that or it will be us.

**Comment by Kducey1** [comment]
So Im not sure how to add the form unless JT knows how to do it:/ Im sure he does, but I removed the map. Would you like me to remove the address off it too? Its on all the contact sections.

**Comment by cbruch** [comment]
Address can stay.
Let's remove this line for now, we have it on the other areas.
Want to stay up to date with our latest news, specials, and promotions? Sign Up for our e-newsletter today!

**Comment by Kducey1** [comment]
The line is removed!
