### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#23]
1. Under our services:
a. Customs designs - EVERY website is custom designed specifically for each customers needs. 
b. Fast - Guaranteed Unlimited Updates are included in our maintenance plans
c. Experience - 18+ years of experience working with customers designing, building, and maintaining websites.
d. devices - Websites are tailored to work and display properly on all device: Phones, Tablets, and Computers!

Latest Creations - need to get you 3 sites for there. 

The boys will have to work on the See ALL link!

**Comment by Kducey1** [comment]
Also I updated the services.

Just let me know when you have the sites for the creations!

**Comment by cbruch** [comment]
http://tqhastallionauction.com/
http://ventureequine.com/
http://www.iqha.com/
http://pinetreervcenter.com/

I like the top three the best for the front page

**Comment by cbruch** [comment]
Home Looks GREAT!
