### ISSUE TITLE
BSID Logo

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#5]
Let's double the size of the BSID Logo in the header (top)

If you can put it in the footer as well under the nav buttons.

**Comment by Kducey1** [comment]
The logo is now bigger and in the footer!

**Comment by cbruch** [comment]
Top logo can it be even bigger?

In footer please put it above we Love creative people & remove that saying. Not sure it fits!

**Comment by Kducey1** [comment]
How does the top logo size look

Also the creative people thing is removed!
