### ISSUE TITLE
Footer Changes

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#6]
Add BSID logo where it says company.

Under the nav add this tag line
 "Our clients all over the US & Canada! We can help no matter where you are!"

Remove all icons except FB icon. Need to add the Godaddy & Authorize Net icon & if you can text below them

1998 - 2016 © Copyright Exceleration Designs, Inc. dba. Big Sky Internet Design. All rights reserved.
All images on this site and any site associated with this site hold a copyright and can not be removed without permission.

**Comment by Kducey1** [comment]
Footer is fixed
