### ISSUE TITLE
What we do on "home page"

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#7]
The image that is on the right how many can we have there??  Might thought is to have screen shots of our work there. Can those rotate on their own rather than having to use buttons??

**Comment by Kducey1** [comment]
That would be cool. I'm not sure how to do that on my own. I'll try and figure it out. If I cant figure it out I'll ask jt  when he comes home

**Comment by cbruch** [comment]
We just need to make the images & replace them named the same as the others there. As far as rotating that I have no clue Jake would.

**Comment by Kducey1** [comment]
I know you don't have the updated link but I actually started to do that for the current images that are there, just minus the slideshow part. Still trying to find a way to send a working link for you.

**Comment by Kducey1** [comment]
Is this the link that you need? 
https://kducey1.github.io/BigSkyInternetDesign/services.html

**Comment by Kducey1** [comment]
So last night we changed the image so you don't have to click it to view the images, and it is now a slide show. What images would you like to go here?

**Comment by cbruch** [comment]
Remove Foster add:
http://pccha.com/
http://www.theraplate.com/
http://lazcar.com/new/site3.asp   but it is not live yet. But can go in for now

**Comment by Kducey1** [comment]
Added them!

**Comment by cbruch** [comment]
Please send me link YUG Can't see the damn things! Have I ever told you I hate computers!

**Comment by Kducey1** [comment]
https://kducey1.github.io/BigSkyInternetDesign/index.html

this should work!
