### ISSUE TITLE
Services - "home page"

### ISSUE THREAD

**Issue by cbruch** [Kducey1/BigSkyInternetDesign#8]
Under the paragraph add "Updates Guaranteed with 24 hours" 

The 4 icons - left justify text. Change text to this per each..

EVERY website is custom designed specifically for each customer. No Cookie-Cutter Templates, ever!!

Unlimited updates included in our updates/maintenance plans. Websites are updated by the close of the next business day - Guaranteed!

We have over 18+ years of experience working with customers designing, building, and maintaining websites. 

Your website will be tailored to work & display properly on all device: Phones, Tablets, & Computers!

**Comment by Kducey1** [comment]
Okay so I added all these to the home page as well. The only thing is the left justified text looks a little odd since everything else is centered. But, if you like it, that is all that matters :)
